**시험문제**

코드는 거의 안나올거


1. OX(거의 나오지 않을 것 같음)

2. 간단한 단답형(개념에 대한 질문)

3. 수식을 푸는 문제(여러 공식 formula에 대한 것 : Bias Variance 쪼개지는 것 등)


---

# Resampling(CV)

데이터 사이즈가 크기 때문에 요즘은 안쓰기도 함. (Validation만 함)

## 1. 이론

### **A. Train set / Test set**

---

**Validation set approach**

* 전체 자료를 랜덤하게 두 그룹으로 분할하여 각각 훈련/평가 자료로 사용, 보통 5:5나 7:3정도로 할당

> 훈련 데이터에서 테스트를 안해버림. 오버피팅 문제가 생길 수 있기 때문임... 현실적인 prediction의 상황을 고려

* 모형의 평가를 평가 데이터에서 계속 하는 것은 좋지 않음. 또한 애초에 평가 데이터를 모르는 경우도 있음. 따라서 훈련 데이터를 쪼개서 검증을 하는 것이 고려됨 : Validation set

> 평가 데이터에서 모형이 어떻게 예측을 할 것인지에 대한 추정, 가장 좋다고 판단되는 모형을 찾은 뒤 다시 데이터를 합쳐 평가 데이터에 적용

상황에 따라서 평가 데이터와 검증 데이터를 합칠 수도 있다. Validation set임에도 Test set이라고 하기도 함. 스까있는 경우 : 애초에 Validation이 Test에 대한 추정치이기도 하니까...

현실에선 훈련과 검증 데이터만 있고, 모델링만 해서 알아서 활용하라는 것도 있음. 이상적인 것은 훈련/검증/평가이긴 함.

5:5는 평가데이터 비중을 맞추기 위해서, 7:3은 모형을 더 잘 훈련시키기 위해서. 3:7처럼 훈련 데이터를 너무 적게 쓰면 제대로 된 평가가 될까에 따른 의심이 들기 때문. 근데 훈련데이터가 충분히 많으면 상관없나?

> 아무튼 적어도 절반은 써라.

`-` Validation Set의 선정

$$\begin{align} \{1, 2, 3, 4, 5, 6\},& ~ \{7, 8, 9, 10\}\\
\{1, 2, 4, 7, 8, 9\},& ~ \{3, 5, 6, 10\}\\
& \vdots\end{align}$$

> 랜덤으로 선정하여 굉장히 많은 경우가 존재함.

`-` 단점

* **랜덤하게 자료를 분할**하기 때문에 분할 결과에 따라 추정의 변동성이 클 수 있음
* 원 자료의 크기보다 작은 집합의 훈련자료가 모형적합에 사용되기 때문에 test error가 과대추정될 수 있음(적합이 덜 되니까)
* 훈련 데이터를 쪼개 훈련/평가(Validation)로 나누고, 실제 적합에서는 훈련 데이터 전체를 사용함.

### **B. Leave-One-Out Cross-Validation(LOOCV)**

---

n-1개의 훈련 데이터와 1개의 평가 데이터(Validation set)로 분할, 총 n개의 모형 구성 후 각 평가 데이터에 대한 오차제곱을 더하여 test error를 추정

$$\begin{align} \text{MSE}_i & = (y_i - \hat y_{(i)})^2, ~ \hat y_{(i)} : i\text{번째 관측치를 제외하고 적합된 모형에 의한 예측치} \\
CV_{(n)} & = \frac1n \underset{i=1}{\overset{n}{\sum}}\text{MSE}_i = \frac1n \underset{i=1}{\overset{n}{\sum}}(y_i - \hat y_{(i)})^2 \end{align}$$

`-` 장점 : 모형 적합에 n-1개를 사용하기 때문에 정보량에 손해가 거의 없음 -> test error의 과대추정 염려로부터 자유로움. 자료의 분할에 따른 불확실성이 나타나지 않음(모든 자료가 똑같이 validation set에 한 번씩 포함)

`-` 단점 : 선형회귀분석을 제외하고 산출하는 데에 계산량이 매우 많아 자료의 크기가 매우 크거나 적합모형의 계산에 시간이 많이 소요되는 경우 적용하기 어려움, 하나의 데이터에서만 예측을 하면(테스트 데이터가 극단적으로 작을 경우) 분산이 커질 수 있음.

* 다항회귀모형의 경우 다음과 같은 단순화가 가능함

$$CV_{(n)} = \frac1n\underset{i=1}{\overset{n}{\sum}}\bigg(\frac{y_i - \hat y_i}{1-h_{ii}}\bigg)^2$$

여기서 $h_{ii}$는 hat matrix의 i번째 대각원소.

> 막 자세히 알 필요는 없음. 그냥 가능하다고만 알아두면 됨?
>
> 일반적으로 전체 모형의 train error보다 커지는 경향이 있음.

위 식으로 한 번의 모형적합을 통해 CV test error를 얻을 수 있음. 하지만, 사용할 수 있는 범위가 좁기 때문에 사용하기 어려움.

### **C. k-fold CV**

---

전체 자료를 $k$개의 집합으로 분할한 후, 그 중 하나의 집합을 평가자료로 설정

$i$번째 평가자료를 이용한 test error 추정치를 $\text{MSE}_i$라고 하면, k-fold에 의한 test error 추정치는 아래와 같다.

$$CV_{(k)} = \frac1k\underset{i=1}{\overset{k}{\sum}}\text{MSE}_i$$

> 이 때, learner 별 공유하는 자료가 존재한다. 집합에 속하는 자료들은 비복원추출으로 선정한다.
>
> fold가 커질 수록 훈련 데이터가 늘어난다. 이에 따라 예측오차가 줄어든다.
>
> 너무 큰 fold를 쓰면 validation set이 줄어들면서 분산이 커질 수 있다.
>
> 통상적으로 k는 5, 10 정도를 사용한다.

`-` 장점

- k번만 모형 적합을 해도 되어 LOOCV에 비해 계산량이 현저히 감소한다.

- LOOCV에 비해 test error의 추정이 오히려 정확한 경우가 종종 발생한다.(훈련 자료의 overlap 경감 효과)

> 백만개의 데이터가 있다, LOOCV를 쓰면 전체 데이터를 쓴 것과 하나의 데이터를 뺀 모형의 차이가 그렇게 크지 않다. 이에 따라 훈련의 예측오차(train MSE)와 test error의 추정값이 거의 같아질 수 있다.

`-` 단점

- k개의 집합으로 분할 시 randomness가 발생한다. 이에 따라 test error 추정 시 변동성이 발생한다. 하지만 Validation set approach(한 번 분할)보다는 훨씬 안정적

`-` CV error는 훈련 데이터가 달라지기 때문에 평균과 분산이 존재한다.

### **D. 분류 문제에서의 CV**

---

교차타당검증법 CV test는 자료를 어떻게 분할할 것인가에 대한 문제이므로 평가측도와는 큰 관련이 없음.

평가자료에서의 오분류율, 민감도, 특이도, AUC 등을 분류기에 대한 지표로 활용할 수 있음.

> 분류문제에서의 LOOCV에 의한 오분류율

$$CV_{(n)} = \frac1n\sum I(y_i \neq \hat y_{(i)})$$

### **E. Test error의 minimizer**

---

test error의 추정 자체에 관심이 있는 경우, 언제 test error가 최소가 되는지에 관심이 있는 경우.

후자의 경우 test error의 과대/과소 추정에는 보다 관대할 수 있음.

true test MSE와, LOOCV estimate와, 10-fold estimate에 대해서 최소화하는 것이 test MSE를 최소화하는 점과 동일하지 않을 수 있음.

k-fold CV : k = 5일 때, 각각 오차제곱합이 나오고, 이들의 평균과 표준오차를 구할 수 있음. MSE CURVE가 있을 때, 최소점에 대한 표준오차 바운더리가 나오고, 그 구간 내의 점 중에서 가장 간단한 모형을 택하는 경우가 많음.

> 최대한 Simple한 모형으로 선택한다.

### **F. Bootstrap**

---

`-` 주어진 데이터의 크기가 n일 때, 각각의 데이터 포인트에 대해서 1/n의 확률을 주고 복원추출함.

`-` 주로 추정량의 분산을 정확히 알기 어려울 때, 이를 알아내는 방법으로 사용함.

$$\begin{align} \hat\theta_1 : Y_{11}, Y_{12}, \cdots, Y_{1n} \sim F \\
\hat\theta_2 : Y_{21}, Y_{22}, \cdots, Y_{2n} \sim F \\ \\ 
Y_1, Y_2, \cdots, Y_n \sim F_n \\
Y_{11}', Y_{12}', \cdots, Y_{1n}' \to \hat \theta^{(1)} \\
Y_{21}', Y_{22}', \cdots, Y_{2n}' \to \hat \theta^{(2)} \\
\vdots \\
Y_{b1}', Y_{b2}', \cdots, Y_{bn}' \to \hat \theta^{(b)}
\end{align}$$

관측된 표본을 모집단으로 하는 분포에서 새로운 subsample을 만들어내는 것.

표본을 sampling하여 산출된 분산이 실제 F의 분산에 수렴한다는 것이 알려져 있다.

> 원래 해야 되는 것은 F인데, 실제로 할 수 없으니까 sample에서 함.

## 2. 실습

**cross validation 코드를 주로 이해하면 됨. 그러면 이 장에서 할 수 있는 걸 완벽하게 이해한 거라고 보면 됨 ㅇㅇ**

### Extraction of Main code

---

In [ ]:
## Validation set approach
valid_pred = results.predict(X_valid)
np.mean((y_valid - valid_pred)**2) ## validation mse(test mse 추정치)

## Cross validation
sklearn.model_selection.train_test_split(df, test_size = "float or int", random_state = "seed")
sklearn.model_selection.KFold(n_splits="int", shuffle="bool", random_state="seed") ## shuffle = True로 randomness 확보
sklearn.model_selection.cross_validate(predictr, X, Y, cv="int or KFold object")

## Bootstrap
indx = np.random.default_rng().choice(n, n, replace = True) ## 복원추출

### **A. 라이브러리 imports**

---

In [2]:
import numpy as np
import statsmodels.api as sm
from ISLP import load_data
from ISLP.models import (ModelSpec as MS, summarize, poly)

from sklearn.model_selection import train_test_split

from functools import partial
from sklearn.model_selection import (cross_validate , KFold , ShuffleSplit) ## CV random split
from sklearn.base import clone
from ISLP.models import sklearn_sm

### **B. 데이터**

---

In [3]:
Auto = load_data('Auto')
Auto_train, Auto_valid = train_test_split(Auto, test_size=100, random_state=0) ## validation을 보고 있음

hp_mm = MS(['horsepower'])
X_train = hp_mm.fit_transform(Auto_train)
y_train = Auto_train['mpg']
model = sm.OLS(y_train, X_train)
results = model.fit()
print(results.summary())

X_valid = hp_mm.transform(Auto_valid)
y_valid = Auto_valid['mpg']
valid_pred = results.predict(X_valid)
train_pred = results.predict(X_train)

print(np.mean((y_train - train_pred)**2)) ## trian mse
print(np.mean((y_valid - valid_pred)**2)) ## validation mse

                            OLS Regression Results                            
Dep. Variable:                    mpg   R-squared:                       0.599
Model:                            OLS   Adj. R-squared:                  0.598
Method:                 Least Squares   F-statistic:                     433.9
Date:                Tue, 22 Oct 2024   Prob (F-statistic):           1.48e-59
Time:                        09:30:23   Log-Likelihood:                -879.71
No. Observations:                 292   AIC:                             1763.
Df Residuals:                     290   BIC:                             1771.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
intercept     39.8828      0.848     47.020      0.0

> train보다 validation의 MSE가 조금 더 작음. 자료의 수가 적으면 이런 상황이 나올 수도 있음

### **C. 훈련 및 검증오차**

---

In [4]:
# 훈련과 검증 오차를 확인하는 함수 생성
# -------------------------------------
def evalMSE(terms, response , train , test):
    mm = MS(terms)
    X_train = mm.fit_transform(train)
    y_train = train[response]
    X_test = mm.transform(test)
    y_test = test[response]
    results = sm.OLS(y_train, X_train).fit()
    test_pred = results.predict(X_test)
    return np.mean((y_test - test_pred)**2)

In [5]:
MSE = np.zeros(3)
for idx, degree in enumerate(range(1, 4)):
    MSE[idx] = evalMSE([poly('horsepower', degree)], 'mpg', Auto_train, Auto_valid) ## 1~3차 회귀모형
MSE

array([23.20193005, 16.99348987, 16.9506061 ])

In [6]:
hp_model = sklearn_sm(sm.OLS, MS(['horsepower']))
X, Y = Auto.drop(columns=['mpg']), Auto['mpg']
cv_results = cross_validate(hp_model, X, Y, cv=Auto.shape[0]) ## 전체 데이터를 넣어주면 알아서 쪼개고 LOOCV
cv_err = np.mean(cv_results['test_score'])
cv_err

24.23151351792922

* 다항식의 차수를 키웠을 때의 교차검증오차(LOOCV)

In [8]:
cv_error = np.zeros(5)
H = np.array(Auto['horsepower'])
M = sklearn_sm(sm.OLS)

for i, d in enumerate(range(1,6)):
  X = np.power.outer(H, np.arange(d+1))
  M_CV = cross_validate(M, X, Y, cv=Auto.shape[0])
  cv_error[i] = np.mean(M_CV['test_score'])

cv_error

array([24.23151352, 19.24821312, 19.33498406, 19.42443029, 19.03320648])

* 셔플을 한 K-fold CV

In [10]:
cv_error = np.zeros(5)
# 40개로 쪼개는 CV
cv = KFold(n_splits=40, shuffle=True, random_state=0) ## shuffle을 꼭 해줘야 함. randomness 확보
print(cv)

# use same splits for each degree for i, d in enumerate(range(1,6)):
X = np.power.outer(H, np.arange(d+1))
for i, d in enumerate(range(1,6)):
    M_CV = cross_validate(M, X, Y, cv=cv) ## 전체 데이터를 먹이고, cv에 KFold object를 입력
    cv_error[i] = np.mean(M_CV['test_score'])
print(cv_error)

KFold(n_splits=40, random_state=0, shuffle=True)
[18.93586159 18.93586159 18.93586159 18.93586159 18.93586159]


* 두 개로 쪼개서 validation error 확인

In [11]:
validation = ShuffleSplit(n_splits=1, test_size=196, random_state=0)
results = cross_validate(hp_model,
Auto.drop(['mpg'], axis=1), Auto['mpg'], cv =validation)
print(results)

{'fit_time': array([0.0047152]), 'score_time': array([0.00140858]), 'test_score': array([23.61661707])}


### **D. Bootstrap**

---

-  $Var ( \alpha X + ( 1- \alpha)Y)$를 최소화하는 문제: 수식에 의해서 $\alpha$에 대한 해는
$$ \frac{ \sigma_Y^2 - \sigma_{XY} }{  \sigma_X^2 + \sigma_Y^2 - 2 \sigma_{XY} }$$

> 분산을 계산하는 게 쉽지 않음. -> bootstrap

In [12]:
# 주어진 데이터의 인덱싱을 통해서 공분산을 얻고 해를 구함
# -------------------------------------------------------
Portfolio = load_data('Portfolio')
def alpha_func(D, idx):
    cov_ = np.cov(D[['X','Y']].loc[idx], rowvar=False)
    return ((cov_[1,1] - cov_[0,1]) / (cov_[0,0]+cov_[1,1]-2*cov_[0,1]))

In [13]:
# 위 함수를 구동
# --------------
rng = np.random.default_rng()
idx = rng.choice(100, 100, replace=True)
idx = range(Portfolio.shape[0])
alpha_func(Portfolio, idx)
# index를 랜덤하게 정해서 결과를 확인

0.57583207459283

In [14]:
def boot_SE(func, D, n=None, B=1000, seed=0):
    rng = np.random.default_rng(seed)
    first_ , second_ = 0, 0
    n = n or D.shape[0]
    for _ in range(B):
        idx = rng.choice(D.index, n, replace=True)
        value = func(D, idx)
        first_ += value
        second_ += value**2
    return np.sqrt(second_ / B - (first_ / B)**2) # 표준편차 계산

alpha_SE = boot_SE(alpha_func, Portfolio ,B=1000, seed=1)
alpha_SE

0.08945522198999856

In [15]:
def boot_OLS(model_matrix, response, D, idx):
   D_ = D.iloc[idx]     #D.iloc #
   Y_ = D_[response]
   X_ = clone(model_matrix).fit_transform(D_)
   return sm.OLS(Y_, X_).fit().params

hp_func = partial(boot_OLS, MS(['horsepower']), 'mpg')
# 함수를 구동할 때 모든 인자가 아니라 필요 인지만 받을 수 있게 함
# 앞에 두 인자는 고정시키게 됨

In [16]:
rng = np.random.default_rng(0)
kk = [hp_func(Auto, rng.choice(392, 392, replace=True)) for _ in range(10)]
print(np.array(kk))

[[39.88064456 -0.1567849 ]
 [38.73298691 -0.14699495]
 [38.31734657 -0.14442683]
 [39.91446826 -0.15782234]
 [39.43349349 -0.15072702]
 [40.36629857 -0.15912217]
 [39.62334517 -0.15449117]
 [39.0580588  -0.14952908]
 [38.66688437 -0.14521037]
 [39.64280792 -0.15555698]]


In [17]:
def boot_OLS(model_matrix, response, D, idx):
   D_ = D.loc[idx]     #D.iloc #
   Y_ = D_[response]
   X_ = clone(model_matrix).fit_transform(D_)
   return sm.OLS(Y_, X_).fit().params

hp_func = partial(boot_OLS, MS(['horsepower']), 'mpg')
hp_se = boot_SE(hp_func, Auto, B=1000, seed=0)
print(hp_se)

hp_model.fit(Auto, Auto['mpg'])
model_se = summarize(hp_model.results_)['std err']
print(model_se)

intercept     0.717654
horsepower    0.006041
dtype: float64
intercept     0.717
horsepower    0.006
Name: std err, dtype: float64


In [18]:
quad_model = MS([poly('horsepower', 2, raw=True)])
quad_func = partial(boot_OLS, quad_model, 'mpg')
print(boot_SE(quad_func, Auto, B=1000))

M = sm.OLS(Auto['mpg'], quad_model.fit_transform(Auto))
print(summarize(M.fit())['std err'])

intercept                                  1.538641
poly(horsepower, degree=2, raw=True)[0]    0.024696
poly(horsepower, degree=2, raw=True)[1]    0.000090
dtype: float64
intercept                                  1.800
poly(horsepower, degree=2, raw=True)[0]    0.031
poly(horsepower, degree=2, raw=True)[1]    0.000
Name: std err, dtype: float64
